/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Userroles = "guest" | "user";

export interface Alias {
    address: string;
    createdAt: Generated<Timestamp>;
    id: Generated<number>;
    updatedAt: Generated<Timestamp>;
    userId: number;
}

export interface User {
    address: string;
    createdAt: Generated<Timestamp>;
    id: Generated<number>;
    pgpPublicKey: string | null;
    publicKey: string;
    role: Generated<Userroles>;
    updatedAt: Generated<Timestamp>;
}

export interface DB {
    Alias: Alias;
    User: User;
}
