/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType, Generated} from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Alias {
    id: Generated<number>;
    userId: number;
    address: string;
    updatedAt: Generated<Timestamp>;
    createdAt: Generated<Timestamp>;
}

export interface User {
    id: Generated<number>;
    address: string;
    pgpPublicKey: string | null;
    publicKey: string;
    role: "guest" | "user";
    updatedAt: Generated<Timestamp>;
    createdAt: Generated<Timestamp>;
}

export interface DB {
    Alias: Alias;
    User: User;
}
